### ISSUE TITLE
Why use express in client folder

### ISSUE THREAD

**Issue by semionvn** [Alexloof/Next-GraphQL-Blog#5]
Hi, i'm using express and apollo server to build server side, react for client but i switch to nextjs for seo frienly. In your project, i dont understand why use express in client folder. Can we use it in server folder and seperate with client (for nextjs and client dependency)

**Comment by Alexloof** [comment]
Hello! Yes i actually have an express server on the server (because apollo server is built on express). Then i also have an express server on the client. The express server on the client is a custom server that belongs to the server side rendering for Next.js. 

You don't need a custom express server for Next.js, but if you want to use other features/customize the server side rendering Next.js give you the option to use a customized express server.

**Comment by semionvn** [comment]
Got it, many thanks
